### ISSUE TITLE
Style file doesn't work

### ISSUE THREAD

**Issue by SturgeonInc** [ErikReider/SwayOSD#146]
This is both by specifying the file location via --style and also automatic search

**Comment by SturgeonInc** [comment]
1. `$HOME/.config/swayosd/style.css`, and note that XDG_CONFIG_HOME=$HOME/.config
2. I have just this at the moment, trying to get it to show up at all: 
```css
window#osd {
  border: #FFFFFF;
  background: #FFFFFF;
  /* border: #E67E80; */
  /* background: #313244; */
}
```
3. Yes, I pkill it and then restart, and check that it's dead by testing an OSD notification (e.g. volume up)

**Comment by SturgeonInc** [comment]
This is my new config file
```CSS
window#osd {
  border: 9px solid #ffffff;
  border-radius: 10px;
  background: alpha(#FFFFFF, 0.8);
}
```
but the result is:

![Image](https://github.com/user-attachments/assets/d1ad9271-189a-4760-b34b-726b1c9f3386)

The border-radius is respected, but the other values are not
